kind: Service
apiVersion: v1
metadata:
  name: djangotracingapp-service
  labels:
    name: djangotracingapp-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: djangotracingapp
  sessionAffinity: None
